### ISSUE TITLE
excluded_exceptions config not being respected

### ISSUE THREAD

**Issue by mbajur** [getsentry/sentry-ruby#1430] opened 2021-05-05 08:36 UTC
**Describe the bug**

I have a following sentry initializer defined yet still i can see the excluded exception being reported to sentry:

```ruby
Sentry.init do |config|
  config.dsn = Figaro.env.sentry_dsn
  config.excluded_exceptions += [
    'ExternalUsers::DistributeOneWorker::PassBookNotGeneratedYetError'
  ]
end
```

![image](https://user-images.githubusercontent.com/581569/117115668-bb578080-ad8d-11eb-861b-8242eaa1f571.png)

**Environment**
 - Ruby Version: 2.5.3
 - SDK Version: 4.3.2
 - Integration Versions (if any): Rails 2.5.3

**Comment by st0012** [comment] 2021-05-06 07:21
I can't reproduce this issue with the apps I have. Can you provide an example repo or more detail on the worker & exception?

**Comment by st0012** [comment] 2021-05-28 07:14
because I can't reproduce the issue, I'm closing it for now.

**Closed by st0012** 2021-05-28 07:14 UTC
Labels: bug

**Comment by Harshit11071998** [comment] 2023-04-28 05:35
I too am facing this issue. 
I have sentry-ruby/rails version 5.9.0
Rails 5.2.4
ruby 2.6.6
