### ISSUE TITLE
Is there any way to disable sending transactions altogether?

### ISSUE THREAD

**Issue by oofoghlu** [getsentry/sentry-ruby#1307] opened 2021-03-02 17:46 UTC
We are having an issue where some of our transactions are being sent to Sentry even though we have "disabled" sampling by setting `config.traces_sample_rate` to `0.0`.

It doesn’t seem to happen consistently and is difficult to reproduce. We are not making any calls to `capture_*` directly.

Is there any way to disable transactions altogether? Or have you any idea why these might be getting sent?

In terms of logs we are getting a lot of `INFO -- sentry: Sending transaction xxxxxxxxx to Sentry` but we aren’t getting any of the logs pertaining to sampling around https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry/transaction.rb#L71-L117 so I am assuming the config is set up correctly and sampling is as good as "disabled" but somehow transactions are getting sent by some other means.

Running on:
sentry-ruby-core (4.2.2)
sentry-rails (4.2.2)
sentry-ruby (4.2.2)

**Comment by st0012** [comment] 2021-03-03 07:01
performance is disabled by default, so this is weird. can you try removing `config.traces_sample_rate` completely and see if it still happens?

**Comment by oofoghlu** [comment] 2021-03-03 09:04
Sorry, I should have said. The first thing I tried was to remove `config.traces_sample_rate` completely and when I saw we were still getting some transactions sent I then made it explicitly set to `0.0`.

I have since tried setting
```
config.traces_sampler = lambda do |sampling_context|
  0.0
end
```
but we still get some transactions sent in this case too as well as the expected logs for discarded transactions.

**Comment by st0012** [comment] 2021-03-03 09:07
can you paste the full configuration you have and also tell me your Rails version? I can't reproduce this issue with the example app and my other projects. so more information would be helpful.

**Comment by oofoghlu** [comment] 2021-03-03 09:21
Our config looks like:
```
Sentry.init do |config|
  config.dsn = 'xxxxxxxxxxx'
  config.environment = ENV.key?('ENVIRONMENT') ? ENV['ENVIRONMENT'] : 'NOTSET'
  config.enabled_environments = %w[DEMO STAGING PRODUCTION]
  config.send_default_pii = false
  config.rails.report_rescued_exceptions = true
  config.release = 'vx.x.x'
end
```

Rails is version `5.1.7`.

**Comment by st0012** [comment] 2021-03-03 09:33
a few questions about the transactions:
1. are those transactions associated with any issues?
2. do they contain any spans? like
<img width="1221" alt="Trace Spans" src="https://user-images.githubusercontent.com/5079556/109784931-896b5600-7c46-11eb-9c7f-e2bcb3dc0c5b.png">

3. do you see any pattern between those transactions? like mostly under certain routes
4. what are those transactions' status?
5. can you get me one of the transaction's trace details?

<img width="1224" alt="Trace Details" src="https://user-images.githubusercontent.com/5079556/109784616-372a3500-7c46-11eb-943b-4dc5f75cc75d.png">

**Comment by oofoghlu** [comment] 2021-03-03 10:12
1. The transactions aren't associated with issues.
2. They don't contain spans
3. Unfortunately I don't see any pattern. The transactions include different GET, POST and PUT requests.
4. The transaction statuses are all either `ok` of `invalid_argument` but these I think are the only statuses that our servers have responded with recently.
5. 
![image](https://user-images.githubusercontent.com/8075598/109790067-e34d2b00-7c08-11eb-9513-64af82932988.png)

**Comment by st0012** [comment] 2021-03-03 10:27
ok I think the information confirmed that the tracing is activated both accidentally and partially.

does your frontend project use Sentry as well? if so, does it enable performance monitoring?
if both of the above are true, can you check if it is sending `sentry-trace` with the request? you can see it as `HTTP_SENTRY_TRACE` header in the Rails app.

I'd also like to see the result of 

```ruby
config.traces_sampler = lambda do |sampling_context|
  puts(sampling_context)
end
```

**Comment by st0012** [comment] 2021-03-03 12:03
yeah I just confirmed that if the Rails app doesn't activate tracing but it receives the `sentry-trace` from the request, it'll record the transaction. this is a bug and I'll fix it.

I still need you to help me confirm that's what happens in your case though 🙂

**Comment by oofoghlu** [comment] 2021-03-03 13:35
This is it! Sorry, I should have noticed this sooner. There is a pattern. All of the requests that are sent to Sentry come from our Python application running `sentry_sdk`. I didn't notice this before because this accounts for the vast majority of the requests to our Rails app.

I can see the trace ids on the transactions from our rails app match up with trace ids in our Python app.

Thanks for your help on this!

**Comment by st0012** [comment] 2021-03-03 14:38
Fixed in #1308

**Closed by st0012** 2021-03-03 14:38 UTC
Labels: bug, sentry-ruby, tracing

**Comment by oofoghlu** [comment] 2021-03-03 14:48
Nice! Thanks @st0012!

This should fix our use case. But just curious: what if tracing is enabled and, for example, `traces_sample_rate` is set to `0.2`. Wouldn't this still result in 100% of requests with the `HTTP_SENTRY_TRACE ` header being sent to Sentry rather than 20% indicated by the config?

**Comment by st0012** [comment] 2021-03-03 15:13
if tracing is enabled, the SDK will check if the sentry trace is sampled (the last digit, 1 for true and 0 for false), and apply it to the transaction. so in such cases, server side sampling will be disabled and only rely on the client side's decision (which is the python app in your case).

**Comment by oofoghlu** [comment] 2021-03-03 15:54
Hmmm, I can think of some scenarios where that might not be the desired behaviour. Just using our set up as an example - our client is a Celery task runner. So every trace in the client is a single Celery task. This could propagate many requests to the rails server.

Because there are few tasks in the client it makes sense that the sample rate there might be 1.0. But each task propagates the trace to potentially hundreds of rails requests so you might not want every one of these sampled. It makes sense to me that you would be able to fine tune the separate components and sample them independently.

Tbh I don't really know a whole lot about distributed tracing. I would wonder how other Sentry clients handle this.
