### ISSUE TITLE
Exception during serialization of event, that has ActiveJob/Sidekiq metadata

### ISSUE THREAD

**Issue by get-dmitry** [getsentry/sentry-ruby#1317] opened 2021-03-05 09:36 UTC
**Describe the bug**

```
  config.async = lambda do |event, hint|
    Sentry::SendEventJob.perform_later(event, hint)
  end
```

If occured event happens inside ActiveJob/Sidekiq job,
and event has Active Job metadata in "Additional Data", attempt of performing Sentry::SendEventJob.perform_later(event, hint) will lead to

```
ActiveJob::SerializationError
Can't serialize a Hash with reserved key "_aj_globalid"
```

**To Reproduce**

Described above.

**Expected behavior**

Correct serialization of event for Sentry::SendEventJob.perform_later, or some workaround to be able properly serialize such event.

**Actual behavior**

Described above.

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version:
  
  sentry-rails (4.2.2)
  sentry-ruby (4.2.2)
  sentry-ruby-core (4.2.2)
  sentry-sidekiq (4.2.1)

 - Integration Versions (if any):

  rails (6.1.3)
  activejob (6.1.3)
  sidekiq (6.1.3)

**Comment by st0012** [comment] 2021-04-04 07:33
@get-dmitry can you tell me what type of errors did you have in the original job (the one that triggered Sentry reporting)?

**Comment by st0012** [comment] 2021-06-11 14:08
closing for now due to unable to reproduce the issue.

**Closed by st0012** 2021-06-11 14:08 UTC
Labels: bug, sentry-rails
