### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration in middleware

### ISSUE THREAD

**Issue by YushengLi** [getsentry/sentry-ruby#1183] opened 2021-01-04 19:45 UTC
**Describe the bug**

After upgrade from `sentry-raven` to `sentry-ruby`, we noticed the random exception `RuntimeError: can't add a new key into hash during iteration in middleware` reported within middlewares

We never got the exception while using `sentry-raven`, it only starts happening after the upgrade, and we are still trying to rule out the root cause

Here's the list of all middlewares we have so far

```shell
$ rails middleware

use Slowpoke::Middleware # `slowpole`
use Sentry::Rails::CaptureExceptions
use Rack::Cors # `rack-cors`
use Rack::Rewrite
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets # `sprockets-redirect`
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Rack::Timeout
use ScoutApm::ErrorService::Middleware # `scout_apm`
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Warden::Manager
use ScoutApm::Middleware # `scout_apm`
use Sentry::Rails::RescuedExceptionInterceptor
use HttpAcceptLanguage::Middleware # `http_accept_language`
use OmniAuth::Strategies::Facebook
run Application.routes
```

Backtrace of the exception

```
RuntimeError: can't add a new key into hash during iteration
  from rack/request.rb:79:in `set_header'
  from action_dispatch/http/request.rb:299:in `request_id='
  from action_dispatch/middleware/request_id.rb:26:in `call'
  from rack/method_override.rb:24:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from action_dispatch/middleware/static.rb:127:in `call'
  from rack/sendfile.rb:110:in `call'
  from action_dispatch/middleware/ssl.rb:74:in `call'
  from rack/rewrite.rb:24:in `call'
  from rack/cors.rb:100:in `call'
  from sentry/rack/capture_exceptions.rb:23:in `block in call'
  from sentry/hub.rb:50:in `with_scope'
  from sentry-ruby.rb:114:in `with_scope'
  from sentry/rack/capture_exceptions.rb:14:in `call'
  from slowpoke/middleware.rb:8:in `call'
  from scout_apm/instruments/middleware_summary.rb:58:in `call'
  from rails/engine.rb:524:in `call'
  from puma/configuration.rb:246:in `call'
  from puma/request.rb:76:in `block in handle_request'
  from puma/thread_pool.rb:337:in `with_force_shutdown'
  from puma/request.rb:75:in `handle_request'
  from puma/server.rb:431:in `process_client'
  from puma/thread_pool.rb:145:in `block in spawn_thread'

```

**To Reproduce**

Here's the tricky part, the exception happens randomly, I haven't figured out a way to reproduce the exception 100%.

**Expected behavior**

**Actual behavior**

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version: 4.1.2 (`sentry-ruby`, `sentry-rails`, `sentry-sidekiq` enabled)
 - Integration Versions (if any):
   - Rails: 5.2.4.4
   - Sidekiq 6.1.2

**Sentry Config**

This is not necessary but could be helpful.

```ruby
Sentry.init do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.enabled_environments = %w[staging production]
  config.release = ENV['GIT_COMMIT']
  config.excluded_exceptions += %w[
    Rack::Timeout::RequestTimeoutError
    ActionController::UnknownFormat
    Faraday::TimeoutError
    Pundit::NotAuthorizedError
    Async::Container::Terminate
    Interrupt
    Koala::Facebook::ServerError
  ]
  config.breadcrumbs_logger = [:active_support_logger]
  config.send_default_pii = true
  config.traces_sample_rate = 0.8
end
```

**Comment by st0012** [comment] 2021-01-06 08:04
Here are some (possibly) related issues I found online:
- https://github.com/rack/rack/issues/589
- https://stackoverflow.com/questions/47768547/runtimeerror-cant-add-a-new-key-into-hash-during-iteration-in-rack

What they and this issue have in common are:
1. The error happens when setting new values to the env hash.
2. The root cause is likely the middleware of a monitoring SDK the user uses: `airbrake` vs `new_relic` vs `sentry-ruby`.

Although there isn't a stable way to reproduce such issues yet, avoid sharing the env data should be a solid solution. So I have added https://github.com/getsentry/sentry-ruby/pull/1186 to give it a try.

**Comment by st0012** [comment] 2021-01-07 09:05
@YushengLi I can't confirm if the PR fixes the issue as I can't reproduce it myself. So please reopen it if you still encounter the same problem after the `4.1.3` release.

**Comment by YushengLi** [comment] 2021-01-11 17:48
Sorry for the slow reply, finally got time to upgrade Sentry Ruby to 4.1.3

After the upgrade, the error still gets reported but less frequently compared with 4.1.2

Also, I would like to ask if Sentry Rails tracing is production-ready. I can only saw operation `rails.request`, yet `sql. active_record `, `process_action. action_controller ` and other action_view related events are not being recorded.

**Comment by st0012** [comment] 2021-01-13 11:27
### Update on the cause

the root cause is that the `active_support_logger` breadcrumbs logger and the instrumentation on `process_action.action_controller` collected the headers/request info from the instrumentation payload. and because the headers/request objects can contain arbitrary data, sometimes even records or classes (this really depends on the libraries and the codebase the user has), it caused `SystemStackError (stack level too deep)` when serializing the issue author's events. 

so when the request reached the `request-id` middleware and tried to insert the header, the background worker was still looping the headers hash infinitely, which then caused `RuntimeError: can't add a new key into hash during iteration`. the backgrounding thing also made this hard to debug, because the `SystemStackError` were swallowed by the worker thread silently.

**Comment by st0012** [comment] 2021-01-14 07:33
Hopefully this can be solved by #1199

**Comment by takamario** [comment] 2021-06-02 18:58
As commented in https://github.com/getsentry/sentry-ruby/pull/1199#issuecomment-773069840, we still get `can't add a new key into hash during iteration`.

**Comment by st0012** [comment] 2021-06-03 08:11
@takamario hey thanks for reporting the problem. I've added https://github.com/getsentry/sentry-ruby/pull/1463 to fix the issue.

**Comment by st0012** [comment] 2021-08-31 13:12
@boof can you tell me which version did you use when encountered the issue?

**Comment by boof** [comment] 2021-08-31 13:13
sentry-ruby-core (4.6.5)

**Comment by st0012** [comment] 2021-08-31 13:20
thanks, I'll revisit the issue recently.

**Comment by st0012** [comment] 2021-09-02 09:38
@boof in your case, did you use any breadcrumb logger in your setup? or can you provide your Sentry configuration when using `sentry-ruby`?

**Comment by boof** [comment] 2021-09-02 10:02
Yes we did use the active_support_logger:

```ruby
Sentry.init do |config|
  config.rails.report_rescued_exceptions = false
  config.breadcrumbs_logger = [:active_support_logger]

  config.async = if Rails.env.test? || Rails.env.development?
                   ->(event, hint) { Sentry::SendEventJob.perform_now event, hint }
                 else
                   ->(event, hint) { Sentry::SendEventJob.perform_later event, hint }
                 end
end
```

**Comment by st0012** [comment] 2021-10-31 11:26
@boof sorry that I was too busy these 2 months and couldn't help you address the issue more actively 😢 
do you know what other issues your team have seen during the trial? I'd like to learn more about them.

@DanAndreasson do you also have the issue? if so, would you mind open a new issue with more detail about it?

**Comment by ixti** [comment] 2022-02-21 15:50
With the above config changes the errors disappeared

**Comment by KJTsanaktsidis** [comment] 2023-03-28 04:48
I debugged this problem in our app too (totally independently, I only found this issue once I'd figured the problem out). I patched our Ruby interpreter and dumped out a full all-threads backtrace every time this error is generated, which gave me the clue that it was related to Sentry breadcrumbs.

In our case, there seem to be two main things causing these errors:

The `sql.active_record` notification includes the connection adapter itself (as the key `:connection`) in the notification payload hash. This is obviously not serializable, but in the process of discovering that, Sentry will attempt to `JSON.dump`/`inspect` it (here: https://github.com/getsentry/sentry-ruby/blob/4d712af25de31fc05f65db4c4f2d89bcaf193002/sentry-ruby/lib/sentry/breadcrumb.rb#L57). That causes some iteration of at least a couple of hashes that are internal to the connection: the type map, and the query cache (we'd seen exceptions thrown from app threads while inserting into both of these).

Datadog's APM instrumentation makes the current span available in all `ActiveSupport::Notifications` under the key `datadog_span` (https://github.com/dataDog/dd-trace-rb/blob/1dc95e27d927978e547c2e12b38cb7e3aff3b92e/lib/datadog/tracing/contrib/active_support/notifications/subscription.rb#L81). This also contains internal hashes (for tags) that are written to by the application thread and simultaneously iterated by the sentry breadcrumb flusher.

For now, I'm going to just turn off the activesupport breadcrumbs as suggested by @ixti . The two issues I identified _could_ be fixed by excluding those keys in `Sentry::Rails::InstrumentPayloadCleanupHelper::IGNORED_DATA_TYPES`, but I worry there is going to be a never-ending fountain of things passed around in activesupport notifications that were never intended to be accessed from different threads. I really can't think of a sustainable way to log these breadcrumbs other than stringifying them synchronously inside the notification subscriber.

**Comment by st0012** [comment] 2023-04-08 20:16
I went through [ActiveSupport Notification](https://guides.rubyonrails.org/active_support_instrumentation.html)'s doc, and it looks like the only remaining values that may be problematic to us would be `connection` and perhaps `binds`, which of both are from the `sql.active_record` event. So if we add them to the `IGNORED_DATA_TYPES` list, we should avoid most of the problems from Rails itself.

And on top of that, we can also filter out non-primitive objects, which should also avoid the span from datadog and reduce the chance of similar issues to pretty low.

**Comment by st0012** [comment] 2023-04-08 21:59
Actually, after checking the [edge Rails guide](https://edgeguides.rubyonrails.org/active_support_instrumentation.html), the data that will NOT be caught by the above approach will grow quite a bit, such as:

- `render_template.action_view`'s `locals`
- `enqueue_all.active_job`'s `jobs`
- `process.action_mailbox`'s `mailbox`
- And probably a couple more

So I agree that we should probably update our approach on this. I imagine the solution will be pretty similar to a hash like:

```rb
{
  "sql.active_record" => {
    allowed_data: [:sql, :name]
  },
  "start_processing.action_controller" => {
    allowed_data: [:controller, :action, :method, :path, :format]
  },
  # ... 
}
```

And we only subscribe to those events and include those data.

**Comment by colszowka** [comment] 2023-04-30 09:59
This isn't stale, based on previous comments

**Closed** 2023-06-21 10:26 UTC
Labels: Type: Bug, Status: Backlog
