### ISSUE TITLE
Errors not automatically captured by Sentry for our staging Rails sever

### ISSUE THREAD

**Issue by AndrewSverdrup** [getsentry/sentry-ruby#1553] opened 2021-08-28 02:40 UTC
**Describe the bug**
I'm working on replacing Bugsnag with Sentry in a Ruby on Rails project. Sentry works perfectly in my local dev environment. Errors are automatically sent to Sentry and can be manually sent to Sentry using `Sentry.capture_message`. When I deploy to our staging server, automatic error reporting does not work, but manual errors sent with `Sentry.capture_message` do work, so it is not an issue with the DSN. I also tried a different Sentry DSN (from a different Sentry account), but the behavior was the same. Are there any known situations that can cause automatic error reporting to not work in some environments?

I noticed that automatic error reporting works fine in Sidekiq jobs in our staging environement. So the issue just affects exceptions that occur in the Rails code.

**To Reproduce**
I unfortunately don't have a reproduction case. Sentry just does not automatically report errors in our staging environment, but it works great in my development environment.

**Expected behavior**
If an error occurs in our rails application, such as a division by 0 error, the error should be logged by Sentry.

**Actual behavior**
On our staging server, Sentry does not detect any errors in the rails application unless `Sentry.capture_message` is called explicitly. Sentry works fine in our Sidekiq workers though.

**Environment**
 - Ruby Version: 2.5.1
 - SDK Version: sentry-ruby-core (4.6.5), sentry-rails (4.6.5), sentry-sidekiq (4.6.5)
   - Also tested with 4.3.0 of those three gems, the behavior didn't change
 - Integration Versions (if any):
  - Rails 5.2.2.1, Sidekiq 6.0.7

We are using the `sentry-ruby-core` gem rather than the 'sentry-ruby' gem because our Faraday gem version is less than 1.0 (0.17.3). Although as I mentioned Sentry works perfectly in my local dev environment, so it doesn't appear to be an issue with the gems.

**Sentry Config**

```ruby
Sentry.init do |config|
  config.dsn = Rails.application.secrets.sentry_dsn
  config.breadcrumbs_logger = %i[active_support_logger http_logger]
  config.debug = true
  config.logger = Sentry::Logger.new('/tmp/sentry-temp.log')
end
```
I also tried using the `config.async` option to send the Sentry errors are sent using a Sidekiq async worker. No errors (except the `Sentry.capture_message` ones) show up in the Sidekiq queue in staging, so the issue is not with the Sentry dashboard. The issue seems to be that the Ruby/Rails Sentry API just doesn't even see the error.

**Comment by st0012** [comment] 2021-08-28 02:45
Can you share your staging-only gems? I suspect it could be caused by some conflicts between gems.

**Comment by AndrewSverdrup** [comment] 2021-08-28 03:10
Thanks for the quick reply! We don't have any staging-only/production-only gems. We do have some development only gems. I just moved the development only gems out of the development group in our Gemfile and deployed to our staging server, but that didn't fix the issue.

**Comment by st0012** [comment] 2021-08-28 03:23
I see. Can you list the middlewares you use? `bundle exec rake middleware`.

Also, do you have some global error capturing mechanism in your `ApplicationController` or custom middlewares?

**Comment by AndrewSverdrup** [comment] 2021-08-28 03:30
I also just noticed that `Sentry.capture_exception` errors aren't sent to Sentry. For example I put these two lines in our code and they both show up in Sentry when I run it locally, but in staging the first one with `Sentry.capture_exception` isn't reported.
```rb
Sentry.capture_exception(StandardError.new('This is an exception'))
Sentry.capture_message("test message")
```

`bundle exec rake middleware` output from staging server:
```
use Sentry::Rails::CaptureExceptions
use Rack::Cors
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Bugsnag::Rack
use Appsignal::Rack::RailsInstrumentation
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Warden::Manager
use Rack::CrawlerDetect
use Sentry::Rails::RescuedExceptionInterceptor
use RescueFromInvalidAuthenticityToken
use OmniAuth::Builder
use Rack::Turnout
run App::Application.routes
```

**Comment by st0012** [comment] 2021-08-28 03:50
Does the log show anything about the `Sentry.capture_exception` call?
I really can't think of anything to block `Sentry.capture_exception` just based on environment difference because it's Rails/Rack independent and only acts based on the SDK's configuration.

**Comment by AndrewSverdrup** [comment] 2021-08-28 04:31
Hmm there hasn't been an entry in the logfile in a few hours. I had tried a couple versions of the Sidekiq gem and that may have caused the logging to break. I'm back on 4.6.5 of the Sidekiq gems and the logfile is still empty. The `Sentry.capture_message` manually reported errors are still the only ones showing up in Sentry.

**Comment by st0012** [comment] 2021-08-28 05:26
I'm sorry but I'm not able to debug the issue with so little information. I can't make random guesses and ask you to try them repeatedly.

**Comment by AndrewSverdrup** [comment] 2021-08-28 05:59
No problem, I will reach back out if I can create a reproduction case. Thanks for your time!

**Comment by st0012** [comment] 2021-09-22 06:33
@AndrewSverdrup I hope you've sorted this problem out now?

**Comment by cecilian** [comment] 2021-09-30 12:28
Unless there's some incredibly dumb mistake I'm making, the same is happening for me but in *development* environment.

ruby-2.7.3
Rails 6.1.3.2
sentry-ruby 4.7.3
I followed the basic install instructions.

In console
- `Sentry.capture_message("test message")`:
dumps the entire Sentry instance in stdout, followed by the line `Sending envelope [event] 3526457bc9764dab90ed1546aed2c594 to Sentry`. The message *is* reported to Sentry.

- `Sentry.capture_exception(ActiveRecord::RecordInvalid.new)`
dumps the entire Sentry instance in stdout, but not the line `Sending envelope [event] 3526457bc9764dab90ed1546aed2c594 to Sentry`. The exception *is* reported to Sentry.

- `1/0`
nothing in stdout, the exception is not reported

Any clue what I may be missing here?
Thank you

**Comment by st0012** [comment] 2021-10-01 14:04
@cecilian that's because the SDK doesn't capture exceptions raised in Rails console. it only automatically captures exceptions raised in:
- rack requests
- rake tasks
- supported background jobs

capturing errors in Rails console is generally not useful but noisy because it'll mostly be human errors (think about all the typos) instead of program errors.
if you want to test automatic error-capturing, I recommend you to place the error in a controller action or a rake task.

**Comment by iker-barriocanal** [comment] 2021-10-20 09:42
Closing this issue due to the lack of information/repro case, and a question that has been answered. Feel free to comment here if you have more information that can help replicate the issue.

Thanks!

**Closed by iker-barriocanal** 2021-10-20 09:42 UTC
Labels: bug
