### ISSUE TITLE
Can't send transactions with SDK 5.0.0, frozen OpenSSL::SSL::SSLContext error

### ISSUE THREAD

**Issue by yorch** [getsentry/sentry-ruby#1695] opened 2022-01-23 13:46 UTC
### Issue Description

I have a Rails 6.1 app that I'm developing, where I have Sentry SDK integrated for a few weeks without problems. After upgrading SDK to `v5.0.0`, I've started seen `Transaction sending failed: can't modify frozen OpenSSL::SSL::SSLContext` message in the Rails logs. See below for a complete error message.

Gemfile:
```
gem 'sentry-ruby'
gem 'sentry-rails'
```

Logs:
```
Sending envelope [transaction] 7c1e1d08ccc076c8b85138ea2bcd5cfa to Sentry
Transaction sending failed: can't modify frozen OpenSSL::SSL::SSLContext: #<OpenSSL::SSL::SSLContext:0x0000000111d593c0 @verify_mode=1, @verify_hostname=true, @max_proto_version=nil, @min_proto_version=769, @cert_store=#<OpenSSL::X509::Store:0x000000010f7938c0 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil>, @session_new_cb=#<Proc:0x0000000111e83c00 /Users/user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1038>>
Unreported Transaction: CustomerController#new
exception happened in background worker: can't modify frozen OpenSSL::SSL::SSLContext: #<OpenSSL::SSL::SSLContext:0x0000000111d593c0 @verify_mode=1, @verify_hostname=true, @max_proto_version=nil, @min_proto_version=769, @cert_store=#<OpenSSL::X509::Store:0x000000010f7938c0 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil>, @session_new_cb=#<Proc:0x0000000111e83c00 /Users/user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1038>>
```

### Reproduction Steps

Upgraded SDK from `4.9.1` to `5.0.0` on a Rails 6.1 app using Ruby 3.1.0, and started seeing the error message described.

### Expected Behavior

Transactions being sent to Sentry as in previous SDK versions.

### Actual Behavior

Getting error messages while Sentry trying to send transactions.

### Ruby Version

3.1.0

### SDK Version

5.0.0

### Integration and Its Version

Rails

**Comment by st0012** [comment] 2022-01-23 13:48
@yorch can you share your SDK configs? It’ll be helpful for debugging, thx.

**Comment by st0012** [comment] 2022-01-23 16:23
While I can't reproduce this issue myself, I think it should be fixed by #1696

**Comment by st0012** [comment] 2022-01-24 09:46
@yorch I'll close this for now as `5.0.1` has been released. But please reopen it if you still see the issue 🙂

**Closed by st0012** 2022-01-24 09:46 UTC
Labels: bug, sentry-ruby

**Comment by yorch** [comment] 2022-01-24 21:19
@st0012 thanks for the prompt response and fix, working great now! much appreciated!
