### ISSUE TITLE
File/attachment uploads

### ISSUE THREAD

**Issue by kornate** [getsentry/sentry-ruby#1548] opened 2021-08-22 10:13 UTC
Practically all the other SDKs support file/attachment uploads.

We are new to Sentry and are looking to capture screenshots for errors.

Is this on the roadmap? Is there a short term workaround or solution?

Thanks!

**Comment by st0012** [comment] 2021-08-23 08:20
Can you share more on how you'd use this feature? Like what screenshots do you generate in the backend and how?
More detail will help us assess the need for this feature and plan the implementation (if we think it's necessary).

**Comment by kornate** [comment] 2021-09-02 09:55
Hi @st0012! More information in how this is supported and used in Sentry.io's other SDKs is here, it's how I heard of the feature: https://blog.sentry.io/2021/02/03/how-to-use-sentry-attachments-with-mobile-applications

For us, we are looking at capturing browser DOM screenshots for errors.

**Comment by st0012** [comment] 2021-09-02 11:03
`sentry-ruby` doesn't run in browsers. how do you plan to capture browser screenshots with it?

**Comment by kornate** [comment] 2021-09-03 15:02
Correct, but sentry-ruby doesn't need to run in the browser. I use other SDKs for selenium testing with ruby. I only need to be able to upload an image blob and attach it to sentry when an error is raised.

It's possible in other SDKs and I imagine that the requirement to upload attachments covers a vast array of possible uses beyond mine alone.

We already save the image blob to file when an error is caught, but it would be a lot easier to trace issues if the ruby SDK supported attachments like your other SDKS.

**Comment by st0012** [comment] 2021-09-03 15:08
I can understand your use case of this feature but it's also the only one I've received at the moment. And given that it's primarily for test environment use, I don't plan to implement this feature just for it. I'm afraid that I'll need some other use cases (particularly production ones) before implementing this.

**Comment by Jcambass** [comment] 2022-01-14 06:49
We're in a concrete situation now where being able to upload file attachments to issues would be really handy.

Our use case is that users can upload CSV files. Those sometimes are not parsable. In those situations it's crucial to have access to the uploaded CSV file (normally we don't store them) in the issue context to debug the problem.

**Comment by st0012** [comment] 2022-01-15 16:39
@Jcambass Thanks for the feedback. That sounds a good use case for me.

@sl0thentr0py Do you think the file attachment feature is suitable for the above case? If it is, do you have any suggestion on how should we proceed this?

**Comment by sl0thentr0py** [comment] 2022-01-15 17:48
Hey @st0012, cool coincidence. We were actually just talking about this yesterday in our Q1 planning.
We plan to roll out proper attachments support for both ruby and python this quarter, so I will likely work on adding it next month approximately.

cc @vladanpaunovic @smeubank

**Comment by st0012** [comment] 2022-01-15 17:50
@sl0thentr0py Wow that sounds great! I just assigned this task to you then 😄

**Comment by sandstrom** [comment] 2023-09-14 09:09
Another use-case we ran into today.

We're parsing PDFs in a Ruby backend, and sometimes those PDFs are broken.

We can dig them out from another system, but being able to upload them as attachments to Sentry would speed up the troubleshooting (make it quicker to reproduce the bug on a developer machine).

**Comment by sandstrom** [comment] 2024-01-31 10:37
Just checking in, are there any plans to bring this SDK to parity with the others, when it comes to attachment support?

Would be awesome! 😄

**Comment by sl0thentr0py** [comment] 2024-02-06 20:11
hey no timeline yet but I'll try to add it soon

**Comment by jerhinesmith** [comment] 2024-03-06 17:50
Adding another datapoint here: we do custom integrations for our customers across various systems using browser automation (in our case, [playwright-ruby-client](https://playwright-ruby-client.vercel.app/)). These are often across legacy systems that have no API or at least no publicly-facing API. Browser automation works, but we run into errors when pages take too long to load or if an unexpected modal pops up when trying to click on a button (just two examples among many). Playwright provides screenshot support and we're logging these errors to sentry, so it would be really nice to correlate the two but logging an error and attaching the screenshot that preceded the error.

**Comment by renchap** [comment] 2024-04-05 16:51
Another usecase: we have jobs working on non-small JSON documents, and it would be very useful to us to be able to attach those documents to the errors when the parsing or processing fails

**Comment by jbarber** [comment] 2024-04-29 10:26
I'll second @renchap 's use case - we sometimes get invalid large JSON documents and I want to be able to report these in Sentry as attachments so we try and understand why they are invalid and therefore what might be causing them to be invalid.

It looks like this has been missing from the Ruby SDK for 3 years?

This page https://docs.sentry.io/platforms/ruby/crons/troubleshooting/ suggests that you can use the API to upload attachments and links to https://docs.sentry.io/product/crons/getting-started/http/#check-in-attachment-optional - but this page doesn't have anything about attachments on it.

**Comment by thatsanicehat** [comment] 2024-06-11 16:03
Adding another request for this feature. Looks like it was intended for release in 2022 but fell off? Any update from the team?

**Closed** 2024-08-08 12:51 UTC
Labels: enhancement

**Comment by sandstrom** [comment] 2024-08-08 13:05
@sl0thentr0py Awesome! 🎉
