### ISSUE TITLE
Oj gem + rails_activesupport_breadcrumbs cause errors to not be displayed/reported

### ISSUE THREAD

**Issue by renchap** [getsentry/sentry-ruby#949] opened 2020-01-19 17:26 UTC
## Summary 
I recently switched JSON processing in a app to [Oj](https://github.com/ohler55/oj) using the Rails compatibility methods (https://github.com/ohler55/oj/blob/develop/pages/Rails.md) and errors in controllers/views started to no longer be displayed or reported:
- in development environment, I get the HTML 500 page and no stacktrace in console or development.log
- in production, errors are no longer sent to Sentry

## How to reproduce

I created a sample Rails app on a branch which reproduces the issue: https://github.com/renchap/rails-test-app/tree/oj-sentry-errors

## Console output showing the problem
```
Started GET "/" for ::1 at 2020-01-19 18:20:01 +0100
Processing by HelloController#index as HTML
  Rendering hello/index.html.erb within layouts/application
  Rendered hello/index.html.erb within layouts/application (Duration: 0.4ms | Allocations: 919)
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms | Allocations: 1414)


Sending event 9677fe085efd4550b2a90c11e5be5b35 to Sentry
```
And nothing is sent to Sentry

## Expected console output

```
Started GET "/" for ::1 at 2020-01-19 18:21:55 +0100
Processing by HelloController#index as HTML
  Rendering hello/index.html.erb within layouts/application
  Rendered hello/index.html.erb within layouts/application (Duration: 0.4ms | Allocations: 899)
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms | Allocations: 1396)

Sending event af46e0d7cf434f80b2d485c5af51dee2 to Sentry
ActionView::Template::Error (divided by 0):
    1: aa
    2:
    3: <%= 1/0 %>

app/views/hello/index.html.erb:3:in `/'
app/views/hello/index.html.erb:3
```

## Probable cause

After some time trying to pinpoint the cause and disabling gems, I found out that this only occurs when `sentry-raven` is configured with `config.rails_activesupport_breadcrumbs = true` **AND** `Oj::Rails.mimic_JSON()` is used.

I do not know this gem's internal well enough to go further, but I guess this has to do with how the breadcrumbs are serialised to JSON?

### Versions
Ruby: 2.6.5 (macOS)
Rails: 6.0.2.1
sentry-raven: 2.13.0
oj: 3.10.0

**Comment by st0012** [comment] 2020-12-10 13:20
@renchap can you migrate to the new SDK `sentry-ruby` and see if you can still reproduce it?

**Comment by st0012** [comment] 2021-01-30 08:42
closing for now.

**Closed by st0012** 2021-01-30 08:42 UTC
Labels: active_job, bug

**Comment by lucaong** [comment] 2021-04-08 20:47
Most likely related to https://github.com/getsentry/sentry-ruby/issues/1389 (see a possible solution at the end of the issue report), which in turn is caused by https://github.com/ohler55/oj/issues/651
